// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testmodels2.proto

package testmodels

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage2 struct {
	AInt32               *int32   `protobuf:"varint,1,req,name=aInt32" json:"aInt32,omitempty"`
	AString              *string  `protobuf:"bytes,2,opt,name=aString" json:"aString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage2) Reset()         { *m = TestMessage2{} }
func (m *TestMessage2) String() string { return proto.CompactTextString(m) }
func (*TestMessage2) ProtoMessage()    {}
func (*TestMessage2) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b4c729f8fc03412, []int{0}
}

func (m *TestMessage2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage2.Unmarshal(m, b)
}
func (m *TestMessage2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage2.Marshal(b, m, deterministic)
}
func (m *TestMessage2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage2.Merge(m, src)
}
func (m *TestMessage2) XXX_Size() int {
	return xxx_messageInfo_TestMessage2.Size(m)
}
func (m *TestMessage2) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage2.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage2 proto.InternalMessageInfo

func (m *TestMessage2) GetAInt32() int32 {
	if m != nil && m.AInt32 != nil {
		return *m.AInt32
	}
	return 0
}

func (m *TestMessage2) GetAString() string {
	if m != nil && m.AString != nil {
		return *m.AString
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMessage2)(nil), "testmodels.TestMessage2")
}

func init() {
	proto.RegisterFile("testmodels2.proto", fileDescriptor_5b4c729f8fc03412)
}

var fileDescriptor_5b4c729f8fc03412 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x49, 0x2d, 0x2e,
	0xc9, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x36, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42,
	0x08, 0x29, 0x39, 0x70, 0xf1, 0x84, 0xa4, 0x16, 0x97, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x1a, 0x09, 0x89, 0x71, 0xb1, 0x25, 0x7a, 0xe6, 0x95, 0x18, 0x1b, 0x49, 0x30, 0x2a, 0x30, 0x69,
	0xb0, 0x06, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0x89, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x13, 0x5f, 0x14, 0x8f, 0x9e, 0x35, 0xc2, 0x44,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x27, 0x10, 0xc0, 0x71, 0x00, 0x00, 0x00,
}
