// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testmodels3.proto

package testmodels

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMessage3 struct {
	AInt32               int32    `protobuf:"varint,1,opt,name=aInt32,proto3" json:"aInt32,omitempty"`
	AString              string   `protobuf:"bytes,2,opt,name=aString,proto3" json:"aString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMessage3) Reset()         { *m = TestMessage3{} }
func (m *TestMessage3) String() string { return proto.CompactTextString(m) }
func (*TestMessage3) ProtoMessage()    {}
func (*TestMessage3) Descriptor() ([]byte, []int) {
	return fileDescriptor_732cfe454ee97050, []int{0}
}

func (m *TestMessage3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMessage3.Unmarshal(m, b)
}
func (m *TestMessage3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMessage3.Marshal(b, m, deterministic)
}
func (m *TestMessage3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMessage3.Merge(m, src)
}
func (m *TestMessage3) XXX_Size() int {
	return xxx_messageInfo_TestMessage3.Size(m)
}
func (m *TestMessage3) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMessage3.DiscardUnknown(m)
}

var xxx_messageInfo_TestMessage3 proto.InternalMessageInfo

func (m *TestMessage3) GetAInt32() int32 {
	if m != nil {
		return m.AInt32
	}
	return 0
}

func (m *TestMessage3) GetAString() string {
	if m != nil {
		return m.AString
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMessage3)(nil), "testmodels.TestMessage3")
}

func init() {
	proto.RegisterFile("testmodels3.proto", fileDescriptor_732cfe454ee97050)
}

var fileDescriptor_732cfe454ee97050 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x49, 0x2d, 0x2e,
	0xc9, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x36, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42,
	0x08, 0x29, 0x39, 0x70, 0xf1, 0x84, 0xa4, 0x16, 0x97, 0xf8, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x1a, 0x0b, 0x89, 0x71, 0xb1, 0x25, 0x7a, 0xe6, 0x95, 0x18, 0x1b, 0x49, 0x30, 0x2a, 0x30, 0x6a,
	0xb0, 0x06, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0x89, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x13, 0x5f, 0x14, 0x8f, 0x9e, 0x35, 0xc2, 0xc4,
	0x24, 0x36, 0xb0, 0x25, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xae, 0x6a, 0x0a, 0x79,
	0x00, 0x00, 0x00,
}
